import type { SourceConfig } from './types';

/**
 * Source categories:
 * - research: AI labs, academic papers, research publications
 * - company: Official product/blog feeds from AI companies
 * - media: Tech/industry news outlets
 * - community: Community platforms (Reddit, HN)
 * - social: Twitter/LinkedIn signals (when API available)
 * - newsletter: Premium newsletters
 */

export const SOURCES: SourceConfig[] = [
  // ═══════════════ TIER 1 — Core AI Labs & Companies ═══════════════
  {
    id: 'openai-blog',
    name: 'OpenAI Blog',
    type: 'rss',
    url: 'https://openai.com/blog/rss.xml',
    site_url: 'https://openai.com/blog',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['models', 'research', 'products'],
  },
  {
    id: 'openai-changelog',
    name: 'OpenAI Changelog',
    type: 'rss',
    url: 'https://openai.com/changelog/feed.xml',
    site_url: 'https://openai.com/changelog',
    tier: 1,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['products', 'models'],
  },
  {
    id: 'anthropic-blog',
    name: 'Anthropic Blog',
    type: 'rss',
    url: 'https://www.anthropic.com/feed.xml',
    site_url: 'https://www.anthropic.com/blog',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['models', 'research', 'safety'],
  },
  {
    id: 'google-deepmind',
    name: 'Google DeepMind',
    type: 'rss',
    url: 'https://blog.google/technology/ai/rss/',
    site_url: 'https://deepmind.google/blog/',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'models'],
  },
  {
    id: 'meta-ai-blog',
    name: 'Meta AI Blog',
    type: 'rss',
    url: 'https://ai.meta.com/blog/rss.xml',
    site_url: 'https://ai.meta.com/blog/',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'models', 'open-source'],
  },
  {
    id: 'mistral-news',
    name: 'Mistral AI News',
    type: 'rss',
    url: 'https://mistral.ai/news/rss.xml',
    site_url: 'https://mistral.ai/news/',
    tier: 1,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['models', 'products'],
  },

  // ═══════════════ TIER 2 — Major AI & Tech Companies ═══════════════
  {
    id: 'nvidia-blog',
    name: 'NVIDIA AI Blog',
    type: 'rss',
    url: 'https://developer.nvidia.com/blog/feed/',
    site_url: 'https://developer.nvidia.com/blog/category/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['hardware', 'research', 'models'],
  },
  {
    id: 'huggingface-blog',
    name: 'Hugging Face Blog',
    type: 'rss',
    url: 'https://huggingface.co/blog/feed.xml',
    site_url: 'https://huggingface.co/blog',
    tier: 2,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['open-source', 'models', 'research'],
  },
  {
    id: 'cohere-blog',
    name: 'Cohere Blog',
    type: 'rss',
    url: 'https://cohere.com/blog/rss.xml',
    site_url: 'https://cohere.com/blog',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['models', 'products', 'research'],
  },
  {
    id: 'xai-news',
    name: 'xAI News',
    type: 'rss',
    url: 'https://x.ai/blog/rss.xml',
    site_url: 'https://x.ai/blog',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['models', 'products'],
  },
  {
    id: 'stability-ai-blog',
    name: 'Stability AI Blog',
    type: 'rss',
    url: 'https://stability.ai/news/rss.xml',
    site_url: 'https://stability.ai/news',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['models', 'research', 'open-source'],
  },

  // ═══════════════ TIER 2 — AI Media & News ═══════════════
  {
    id: 'the-decoder',
    name: 'The Decoder',
    type: 'rss',
    url: 'https://the-decoder.com/feed/',
    site_url: 'https://the-decoder.com',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'products', 'research'],
  },
  {
    id: 'venturebeat-ai',
    name: 'VentureBeat AI',
    type: 'rss',
    url: 'https://venturebeat.com/category/ai/feed/',
    site_url: 'https://venturebeat.com/category/ai/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['business', 'news', 'startups'],
  },
  {
    id: 'techcrunch-ai',
    name: 'TechCrunch AI',
    type: 'rss',
    url: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    site_url: 'https://techcrunch.com/category/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['business', 'news', 'startups'],
  },
  {
    id: 'arstechnica-ai',
    name: 'Ars Technica AI',
    type: 'rss',
    url: 'https://feeds.arstechnica.com/arstechnica/index/',
    site_url: 'https://arstechnica.com/ai/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'policy'],
  },

  // ═══════════════ TIER 3 — Specialized AI & Research ═══════════════
  {
    id: 'two-minute-papers',
    name: 'Two Minute Papers',
    type: 'rss',
    url: 'https://medium.com/feed/two-minute-papers',
    site_url: 'https://medium.com/two-minute-papers',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['research', 'news'],
  },
  {
    id: 'marktechpost',
    name: 'MarkTechPost',
    type: 'rss',
    url: 'https://www.marktechpost.com/feed/',
    site_url: 'https://www.marktechpost.com',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['research', 'news'],
  },
  {
    id: 'syncedreview',
    name: 'Synced Review',
    type: 'rss',
    url: 'https://syncedreview.com/feed/',
    site_url: 'https://syncedreview.com',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['research', 'news', 'china'],
  },

  // ═══════════════ TIER 3 — Product & Startup News ═══════════════
  {
    id: 'producthunt-ai',
    name: 'Product Hunt AI',
    type: 'rss',
    url: 'https://www.producthunt.com/feed?category=artificial-intelligence',
    site_url: 'https://www.producthunt.com/categories/artificial-intelligence',
    tier: 3,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['startups', 'products'],
  },

  // ═══════════════ TIER 3 — Policy & Regulation ═══════════════
  {
    id: 'eu-ai-act',
    name: 'EU AI Act Updates',
    type: 'rss',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/european-approach-artificial-intelligence',
    site_url: 'https://digital-strategy.ec.europa.eu/en/policies/european-approach-artificial-intelligence',
    tier: 3,
    language: 'en',
    category: 'media',
    active: false,
    topics: ['policy', 'regulation'],
  },

  // ═══════════════ TIER 1 — Additional AI Labs & Research ═══════════════
  {
    id: 'arxiv-cs-ai',
    name: 'arXiv cs.AI',
    type: 'rss',
    url: 'http://export.arxiv.org/rss/cs.AI',
    site_url: 'https://arxiv.org/list/cs.AI/recent',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'papers'],
  },
  {
    id: 'arxiv-cs-lg',
    name: 'arXiv cs.LG',
    type: 'rss',
    url: 'http://export.arxiv.org/rss/cs.LG',
    site_url: 'https://arxiv.org/list/cs.LG/recent',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'papers', 'models'],
  },
  {
    id: 'arxiv-cs-cl',
    name: 'arXiv cs.CL',
    type: 'rss',
    url: 'http://export.arxiv.org/rss/cs.CL',
    site_url: 'https://arxiv.org/list/cs.CL/recent',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'papers', 'nlp'],
  },
  {
    id: 'nature-ai',
    name: 'Nature AI',
    type: 'rss',
    url: 'https://www.nature.com/subjects/artificial-intelligence.rss',
    site_url: 'https://www.nature.com/subjects/artificial-intelligence',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'papers'],
  },
  {
    id: 'springer-ai',
    name: 'Springer AI Research',
    type: 'rss',
    url: 'https://link.springer.com/search.rss?facet-content-type=Article&query=artificial+intelligence',
    site_url: 'https://link.springer.com',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'papers'],
  },
  {
    id: 'papers-with-code',
    name: 'Papers With Code',
    type: 'rss',
    url: 'https://paperswithcode.com/research.rss',
    site_url: 'https://paperswithcode.com',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'papers', 'open-source'],
  },
  {
    id: 'msr-ai',
    name: 'Microsoft Research AI',
    type: 'rss',
    url: 'https://www.microsoft.com/en-us/research/feed/ai/',
    site_url: 'https://www.microsoft.com/en-us/research/topic/artificial-intelligence/',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'models'],
  },
  {
    id: 'nejm-ai',
    name: 'NEJM AI',
    type: 'rss',
    url: 'https://ai.nejm.org/rss/current.xml',
    site_url: 'https://ai.nejm.org',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'healthcare'],
  },

  // ═══════════════ TIER 2 — Additional AI Media ═══════════════
  {
    id: 'the-verge-ai',
    name: 'The Verge AI',
    type: 'rss',
    url: 'https://www.theverge.com/ai-artificial-intelligence/rss/index.xml',
    site_url: 'https://www.theverge.com/ai-artificial-intelligence',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'products', 'policy'],
  },
  {
    id: 'wired-ai',
    name: 'Wired AI',
    type: 'rss',
    url: 'https://www.wired.com/feed/tag/ai/latest/rss',
    site_url: 'https://www.wired.com/tag/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'policy'],
  },
  {
    id: 'mit-tech-review',
    name: 'MIT Tech Review AI',
    type: 'rss',
    url: 'https://www.technologyreview.com/feed/',
    site_url: 'https://www.technologyreview.com/topic/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['research', 'news', 'policy'],
  },
  {
    id: 'zdnet-ai',
    name: 'ZDNet AI',
    type: 'rss',
    url: 'https://www.zdnet.com/topic/artificial-intelligence/rss.xml',
    site_url: 'https://www.zdnet.com/topic/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'business', 'products'],
  },
  {
    id: 'cnbc-ai',
    name: 'CNBC AI',
    type: 'rss',
    url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100731301',
    site_url: 'https://www.cnbc.com/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'business', 'policy'],
  },
  {
    id: 'bloomberg-ai',
    name: 'Bloomberg AI',
    type: 'rss',
    url: 'https://feeds.bloomberg.com/markets/news.rss',
    site_url: 'https://www.bloomberg.com/artificial-intelligence',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'business', 'policy'],
  },
  {
    id: 'reuters-ai',
    name: 'Reuters AI',
    type: 'rss',
    url: 'https://www.reutersagency.com/feed/?taxonomy=best-sectors&post_type=best&best-sectors=artificial-intelligence',
    site_url: 'https://www.reuters.com/technology/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'business', 'policy'],
  },
  {
    id: 'ft-ai',
    name: 'Financial Times AI',
    type: 'rss',
    url: 'https://www.ft.com/technology/artificial-intelligence?format=rss',
    site_url: 'https://www.ft.com/technology/artificial-intelligence',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'business', 'policy'],
  },
  {
    id: 'the-guardian-ai',
    name: 'The Guardian AI',
    type: 'rss',
    url: 'https://www.theguardian.com/technology/artificialintelligenceai/rss',
    site_url: 'https://www.theguardian.com/technology/artificialintelligenceai',
    tier: 2,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'policy', 'research'],
  },

  // ═══════════════ TIER 2 — Open Source & Developer ═══════════════
  {
    id: 'pytorch-blog',
    name: 'PyTorch Blog',
    type: 'rss',
    url: 'https://pytorch.org/blog/feed.xml',
    site_url: 'https://pytorch.org/blog/',
    tier: 2,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['open-source', 'research', 'models'],
  },
  {
    id: 'tensorflow-blog',
    name: 'TensorFlow Blog',
    type: 'rss',
    url: 'https://blog.tensorflow.org/feeds/posts/default',
    site_url: 'https://blog.tensorflow.org',
    tier: 2,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['open-source', 'research', 'models'],
  },
  {
    id: 'github-blog-ai',
    name: 'GitHub Blog AI',
    type: 'rss',
    url: 'https://github.blog/category/artificial-intelligence/feed/',
    site_url: 'https://github.blog/category/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['open-source', 'products', 'developer'],
  },
  {
    id: 'huggingface-daily-papers',
    name: 'Hugging Face Daily Papers',
    type: 'rss',
    url: 'https://huggingface.co/papers/feed',
    site_url: 'https://huggingface.co/papers',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'papers', 'open-source'],
  },

  // ═══════════════ TIER 2 — Specialized AI Media ═══════════════
  {
    id: 'ai-alignment',
    name: 'AI Alignment Forum',
    type: 'rss',
    url: 'https://www.alignmentforum.org/feed.xml',
    site_url: 'https://www.alignmentforum.org',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'safety', 'alignment'],
  },
  {
    id: 'lesswrong-ai',
    name: 'LessWrong AI',
    type: 'rss',
    url: 'https://www.lesswrong.com/feed.xml',
    site_url: 'https://www.lesswrong.com/tag/ai',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'safety', 'alignment'],
  },
  {
    id: 'oreilly-ai',
    name: 'O\'Reilly AI',
    type: 'rss',
    url: 'https://www.oreilly.com/radar/topics/ai/feed/',
    site_url: 'https://www.oreilly.com/radar/topics/ai/',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'developer'],
  },
  {
    id: 'datacamp-ai',
    name: 'DataCamp AI',
    type: 'rss',
    url: 'https://www.datacamp.com/blog/category/artificial-intelligence/rss.xml',
    site_url: 'https://www.datacamp.com/blog/category/artificial-intelligence',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['research', 'developer', 'news'],
  },

  // ═══════════════ TIER 3 — Community & Social Signals ═══════════════
  {
    id: 'hn-ai',
    name: 'HackerNews AI',
    type: 'rss',
    url: 'https://hnrss.org/frontpage?q=AI&count=10',
    site_url: 'https://news.ycombinator.com',
    tier: 2,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['community', 'tech', 'news'],
  },
  {
    id: 'reddit-ml',
    name: 'r/MachineLearning',
    type: 'rss',
    url: 'https://www.reddit.com/r/MachineLearning/.rss',
    site_url: 'https://www.reddit.com/r/MachineLearning/',
    tier: 2,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['community', 'research', 'papers'],
  },
  {
    id: 'reddit-artificial',
    name: 'r/Artificial',
    type: 'rss',
    url: 'https://www.reddit.com/r/artificial/.rss',
    site_url: 'https://www.reddit.com/r/artificial/',
    tier: 3,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['community', 'news'],
  },
  {
    id: 'reddit-localLLaMA',
    name: 'r/LocalLLaMA',
    type: 'rss',
    url: 'https://www.reddit.com/r/LocalLLaMA/.rss',
    site_url: 'https://www.reddit.com/r/LocalLLaMA/',
    tier: 2,
    language: 'en',
    category: 'community',
    active: true,
    topics: ['community', 'open-source', 'models'],
  },

  // ═══════════════ TIER 3 — Chinese AI (机器之心 / 量子位 / 36氪 / 雷锋网) ═══════════════
  {
    id: 'jiqizhixin',
    name: '机器之心 (JiQiZhiXin)',
    type: 'rss',
    url: 'https://www.jiqizhixin.com/rss',
    site_url: 'https://www.jiqizhixin.com',
    tier: 2,
    language: 'zh',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'china'],
  },
  {
    id: 'qbitai',
    name: '量子位 (QbitAI)',
    type: 'rss',
    url: 'https://www.qbitai.com/feed',
    site_url: 'https://www.qbitai.com',
    tier: 2,
    language: 'zh',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'china'],
  },
  {
    id: '36kr-ai',
    name: '36氪 AI',
    type: 'rss',
    url: 'https://36kr.com/motif/artificial-intelligence/rss',
    site_url: 'https://36kr.com',
    tier: 2,
    language: 'zh',
    category: 'media',
    active: true,
    topics: ['news', 'business', 'china'],
  },
  {
    id: 'leiphone-ai',
    name: '雷锋网 AI',
    type: 'rss',
    url: 'https://www.leiphone.com/category/ai/feed',
    site_url: 'https://www.leiphone.com/category/ai',
    tier: 3,
    language: 'zh',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'china'],
  },

  // ═══════════════ TIER 3 — European AI Media ═══════════════
  {
    id: 'le-monde-ia',
    name: 'Le Monde IA',
    type: 'rss',
    url: 'https://www.lemonde.fr/intelligence-artificielle/rss_full.xml',
    site_url: 'https://www.lemonde.fr/intelligence-artificielle/',
    tier: 3,
    language: 'fr',
    category: 'media',
    active: true,
    topics: ['news', 'policy', 'research'],
  },
  {
    id: 'les-echos-tech',
    name: 'Les Echos Tech',
    type: 'rss',
    url: 'https://www.lesechos.fr/tech-medias/rss',
    site_url: 'https://www.lesechos.fr/tech-medias/intelligence-artificielle',
    tier: 3,
    language: 'fr',
    category: 'media',
    active: true,
    topics: ['news', 'business', 'startups'],
  },
  {
    id: 'euro-ai-watch',
    name: 'EU AI Watch',
    type: 'rss',
    url: 'https://ai-watch.ec.europa.eu/publications/rss',
    site_url: 'https://ai-watch.ec.europa.eu',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['policy', 'research', 'regulation'],
  },

  // ═══════════════ TIER 3 — Industry Vertical Media ═══════════════
  {
    id: 'analytics-vidhya',
    name: 'Analytics Vidhya',
    type: 'rss',
    url: 'https://www.analyticsvidhya.com/blog/feed/',
    site_url: 'https://www.analyticsvidhya.com/blog/category/artificial-intelligence/',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'developer'],
  },
  {
    id: 'towards-data-science-ai',
    name: 'Towards Data Science AI',
    type: 'rss',
    url: 'https://towardsdatascience.com/feed',
    site_url: 'https://towardsdatascience.com',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'developer'],
  },
  {
    id: 'assemblyai-blog',
    name: 'AssemblyAI Blog',
    type: 'rss',
    url: 'https://www.assemblyai.com/blog/rss/',
    site_url: 'https://www.assemblyai.com/blog',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['research', 'models', 'developer'],
  },
  {
    id: 'langchain-blog',
    name: 'LangChain Blog',
    type: 'rss',
    url: 'https://blog.langchain.dev/rss/',
    site_url: 'https://blog.langchain.dev',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['developer', 'agents', 'open-source'],
  },
  {
    id: 'anyscale-blog',
    name: 'Anyscale / Ray Blog',
    type: 'rss',
    url: 'https://www.anyscale.com/blog/feed.xml',
    site_url: 'https://www.anyscale.com/blog',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['developer', 'models', 'infrastructure'],
  },
  {
    id: 'weights-biases-blog',
    name: 'Weights & Biases Blog',
    type: 'rss',
    url: 'https://wandb.ai/feed',
    site_url: 'https://wandb.ai/articles',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['developer', 'research', 'models'],
  },
  {
    id: 'replicate-blog',
    name: 'Replicate Blog',
    type: 'rss',
    url: 'https://replicate.com/blog/feed.xml',
    site_url: 'https://replicate.com/blog',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['models', 'products', 'open-source'],
  },
  {
    id: 'perplexity-blog',
    name: 'Perplexity AI Blog',
    type: 'rss',
    url: 'https://blog.perplexity.ai/feed.xml',
    site_url: 'https://blog.perplexity.ai',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['products', 'search', 'models'],
  },
  {
    id: 'character-ai-blog',
    name: 'Character.AI Blog',
    type: 'rss',
    url: 'https://blog.character.ai/rss/',
    site_url: 'https://blog.character.ai',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['products', 'models'],
  },
  {
    id: 'ai-weirdness',
    name: 'AI Weirdness',
    type: 'rss',
    url: 'https://www.aiweirdness.com/rss/',
    site_url: 'https://www.aiweirdness.com',
    tier: 3,
    language: 'en',
    category: 'media',
    active: true,
    topics: ['news', 'research', 'culture'],
  },
  {
    id: 'import-ai',
    name: 'Import AI (Jack Clark)',
    type: 'rss',
    url: 'https://jack-clark.net/feed/',
    site_url: 'https://jack-clark.net',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'news', 'policy'],
  },
  {
    id: 'interconnects-ai',
    name: 'Interconnects (Nathan Lambert)',
    type: 'rss',
    url: 'https://www.interconnects.ai/feed/',
    site_url: 'https://www.interconnects.ai',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'models', 'open-source'],
  },
  {
    id: 'latent-space',
    name: 'Latent Space',
    type: 'rss',
    url: 'https://www.latent.space/feed',
    site_url: 'https://www.latent.space',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'news', 'developer'],
  },
  {
    id: 'microsoft-copilot-blog',
    name: 'Microsoft Copilot Blog',
    type: 'rss',
    url: 'https://www.microsoft.com/en-us/microsoft-365/blog/category/microsoft-copilot/feed/',
    site_url: 'https://www.microsoft.com/en-us/microsoft-365/blog/category/microsoft-copilot/',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['products', 'business'],
  },
  {
    id: 'google-ai-blog',
    name: 'Google AI Blog',
    type: 'rss',
    url: 'https://blog.google/technology/ai/rss/',
    site_url: 'https://blog.google/technology/ai/',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'products', 'models'],
  },
  {
    id: 'apple-ml-research',
    name: 'Apple ML Research',
    type: 'rss',
    url: 'https://machinelearning.apple.com/rss.xml',
    site_url: 'https://machinelearning.apple.com',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'models'],
  },
  {
    id: 'amazon-science',
    name: 'Amazon Science',
    type: 'rss',
    url: 'https://www.amazon.science/feed',
    site_url: 'https://www.amazon.science/tag/artificial-intelligence',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'ai'],
  },
  {
    id: 'ibm-ai-research',
    name: 'IBM AI Research',
    type: 'rss',
    url: 'https://research.ibm.com/feeds/topic/artificial-intelligence.xml',
    site_url: 'https://research.ibm.com/topics/artificial-intelligence',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'models'],
  },
  {
    id: 'baidu-research',
    name: 'Baidu Research',
    type: 'rss',
    url: 'https://research.baidu.com/feed',
    site_url: 'https://research.baidu.com',
    tier: 3,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'china', 'models'],
  },
  {
    id: 'salesforce-ai',
    name: 'Salesforce AI Research',
    type: 'rss',
    url: 'https://www.salesforce.com/news/category/artificial-intelligence/feed/',
    site_url: 'https://www.salesforce.com/news/category/artificial-intelligence/',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['research', 'products', 'business'],
  },
  {
    id: 'databricks-blog',
    name: 'Databricks AI Blog',
    type: 'rss',
    url: 'https://www.databricks.com/blog/ai/feed',
    site_url: 'https://www.databricks.com/blog/category/ai',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['products', 'data', 'infrastructure'],
  },
  {
    id: 'anthropic-research',
    name: 'Anthropic Research',
    type: 'rss',
    url: 'https://www.anthropic.com/research/feed.xml',
    site_url: 'https://www.anthropic.com/research',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'safety', 'alignment'],
  },
  {
    id: 'eleuther-ai',
    name: 'EleutherAI Blog',
    type: 'rss',
    url: 'https://blog.eleuther.ai/rss/',
    site_url: 'https://blog.eleuther.ai',
    tier: 2,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'open-source', 'alignment'],
  },
  {
    id: 'together-ai-blog',
    name: 'Together AI Blog',
    type: 'rss',
    url: 'https://www.together.ai/blog/rss.xml',
    site_url: 'https://www.together.ai/blog',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['models', 'products', 'infrastructure'],
  },
  {
    id: 'fireworks-ai-blog',
    name: 'Fireworks AI Blog',
    type: 'rss',
    url: 'https://fireworks.ai/blog/rss.xml',
    site_url: 'https://fireworks.ai/blog',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['models', 'products', 'infrastructure'],
  },
  {
    id: 'cognition-labs',
    name: 'Cognition Labs Blog',
    type: 'rss',
    url: 'https://cognition.ai/blog/rss.xml',
    site_url: 'https://cognition.ai/blog',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['agents', 'products', 'startups'],
  },
  {
    id: 'adept-ai-blog',
    name: 'Adept AI Blog',
    type: 'rss',
    url: 'https://www.adept.ai/blog/rss.xml',
    site_url: 'https://www.adept.ai/blog',
    tier: 3,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['agents', 'products', 'research'],
  },
  {
    id: 'anthropic-engineering',
    name: 'Anthropic Engineering',
    type: 'rss',
    url: 'https://engineering.anthropic.com/feed.xml',
    site_url: 'https://engineering.anthropic.com',
    tier: 2,
    language: 'en',
    category: 'company',
    active: true,
    topics: ['developer', 'research', 'engineering'],
  },
  {
    id: 'openai-research',
    name: 'OpenAI Research',
    type: 'rss',
    url: 'https://openai.com/research/rss.xml',
    site_url: 'https://openai.com/research',
    tier: 1,
    language: 'en',
    category: 'research',
    active: true,
    topics: ['research', 'models', 'safety'],
  },
];

/**
 * Get active sources only
 */
export function getActiveSources(): SourceConfig[] {
  return SOURCES.filter((s) => s.active);
}

/**
 * Get sources by category
 */
export function getSourcesByCategory(category: string): SourceConfig[] {
  return SOURCES.filter((s) => s.category === category && s.active);
}

/**
 * Get source by ID
 */
export function getSourceById(id: string): SourceConfig | undefined {
  return SOURCES.find((s) => s.id === id);
}

/**
 * Get sources by topic
 */
export function getSourcesByTopic(topic: string): SourceConfig[] {
  return SOURCES.filter((s) => s.topics?.includes(topic) && s.active);
}
